### ISSUE TITLE
Shared directory giving error on user login 

### ISSUE THREAD

**Issue by chintus777** [abcdesktopio/pyos#11]
Hello Alexandre,

I was trying to implement shared directory for user group using an NFS server.

Following is the snippet which I added in od.config

desktop.policies: {
 'acls' : {},
 'rules': {
   'volumes': {
     'ship': {
       'type': 'nfs',
       'name': 'shared_directory',
       'server': 'x.x.x.',
       'path': '/mnt/partition1',
       'mountPath': '/newmnt'
        },

'ship' is the label of a keycloak group which I have defined in rules in external auth-

            'acl'   : { 'permit': [ 'all' ] },
            'rules' : {
              'rule-net-home': {
               'conditions' : [ { 'memberOf': 'abcdesktop', 'expected' : True } ],
                'expected'   : True,
                'label'      : 'ship'
              },

Following is the error which I am getting on login screen and in pyos logs as well-

Warning FailedMount MountVolume.SetUp failed for volume "nfs-shared-directory-12b58332-1fb8-42b7-bf08-d3a9f515cc7d" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs x.x.x.x:/mnt/partition1 /var/lib/kubelet/pods/0722cb7e-6099-4d43-8ecf-ff4fd8046115/volumes/kubernetes.io~nfs/nfs-shared-directory-12b58332-1fb8-42b7-bf08-d3a9f515cc7d
Output: mount: /var/lib/kubelet/pods/0722cb7e-6099-4d43-8ecf-ff4fd8046115/volumes/kubernetes.io~nfs/nfs-shared-directory-12b58332-1fb8-42b7-bf08-d3a9f515cc7d: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.

Earlier when I was using abcdektopio/oc.pyos:3.0 and auth using ldap with same conf files and on same cluster , shared directory was working fine , but now when I am using abcdesktopio/oc.pyos:3.1 and auth using keycloak , then I am getting this error.

Also I tried to manually add the nfs-common  package inside pyos , but still I am getting same error.
Please resolve this as soon as possible.

Thanks and Regards
Chintu

**Comment by alexandredevely** [comment]
Hello Chintu,

Thank you for your message and for the log information.
The mount command is executed by the worker node. 
You read "bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount. helper program"

Can you confirm that your worker nodes can run your mount command ( I mean that nfs-common is installed and that the nfs mount command works ) ?

Thank you
Alexandre

**Comment by chintus777** [comment]
Hello Alexandre,

Thanks a lot for your reply , Actually I had installed nfs-common on worker nodes but earlier I mounted the folder only on one worker node , now I mounted the folder on each worker node i.e I made each node an nfs-client , now issue is resolved.

Regards
Chintu
