### ISSUE TITLE
Changing namespace 

### ISSUE THREAD

**Issue by Disha5harma** [abcdesktopio/pyos#8]
Hello Alexandre

I wanted to change the namespace of the pyos image (testing to provide seperate namespace for each user & for argo CI/CD implementation). I have done changes in settings.py and od.config.reference while making the image using dockerfile provided in oc.pyos and pyos repo . I am facing few challenges while deploying this .

<img width="757" alt="image" src="https://github.com/abcdesktopio/pyos/assets/43859859/250f1710-c815-4ff7-ad4c-9032beafa8b1">

Also what is the use of od.config.refererence when I am using separate od.config while deploying abcdesktop , what changes are required in both of them ?
Also other thing I observed is that when I deploy daemonset-pyos using abcdesktopio/oc.pyos:3.0 , there are certain files that are missing in /var/pyos/oc/od   
<img width="734" alt="image" src="https://github.com/abcdesktopio/pyos/assets/43859859/4184911c-6b2e-473a-b775-37979ebc3421">

While making the pyos image from dockerfile , i am using this folder with these files as below (as specified in pyos repo).
<img width="744" alt="image" src="https://github.com/abcdesktopio/pyos/assets/43859859/5bfabc3d-c4e4-4451-bb84-4104da93b545">

As I can see some files such as infra.py , postponeapp.py etc.  are missing inside daemonset but are present in pyos repo so I used them when making image. Also some files such as services.py are different in the repo and inside daemonset using default image .
Can please guide which files should I modify for changing namespace 

Thanks and please reply as soon as possible. Early reply is much appreciated.

**Comment by alexandredevely** [comment]
Hi Disha,

You can change the default namespace 'abcdesktop' by your own.
You need to update [od.config](https://raw.githubusercontent.com/abcdesktopio/conf/main/reference/od.config.3.0) file to change the line

```
namespace: 'abcdesktop'
```

And update the yaml file with your own namespace.

I pushed some examples  with the new namespace 'ns-abcdesktop'.

- [ns-abcdesktop.yaml](https://raw.githubusercontent.com/abcdesktopio/conf/main/kubernetes/change-ns/ns-abcdesktop.yaml)
- [ns-install.sh](https://raw.githubusercontent.com/abcdesktopio/conf/main/kubernetes/change-ns/ns-install.sh)
- [ns-poduser.yaml](https://raw.githubusercontent.com/abcdesktopio/conf/main/kubernetes/change-ns/ns-poduser.yaml)
- [od.config](https://raw.githubusercontent.com/abcdesktopio/conf/main/kubernetes/change-ns/od.config)

If you're looking for the source code, use the `3.0` branch of [pyos](https://github.com/abcdesktopio/pyos/tree/3.0)

See you 
Alexandre

**Comment by Disha5harma** [comment]
Thanks a lot Alexandre , this is working fine , I have deployed 3 different namespace in same cluster and tested the same.
